### ISSUE TITLE
Refactor anonymous forums integration for Moodle 3.7

### ISSUE THREAD

**Issue by mackensen** [CLAMP-IT/moodle#3]
The core hack breaks hard with all the changes in mod/forum for 3.7 and will need to be reimplemented.

**Comment by rlorenzo** [comment]
@mackensen Is this reimplementation not fixed? Because it appears that mod/forum/externallib.php would also need to be patched for the inline forum posts that are in the new forum system.

<Nevermind> We found a workaround.The post object in https://github.com/CLAMP-IT/moodle/blob/LAE_37_STABLE/mod/forum/externallib.php#L1221 did not have hiddenuser value, but we just queried for it since we have the postid.

**Comment by mackensen** [comment]
@rlorenzo We overlooked that when refactoring; thanks for the heads-up.

**Comment by andyzito** [comment]
So if I'm understanding this issue correctly, the behavior being requested is that when a user replies to a forum post inline -- that is, navigates to a discussion topic and clicks "reply" in the bottom right of any post block -- they should have the option to post anonymously.

I'm actually not sure that's something we need to support -- the advanced link is there for things like posting anonymously or other more complex settings; the inline reply is for quick, settings-light replies. Thoughts? Am I misinterpreting the issue here?

**Comment by rlorenzo** [comment]
It's not obvious that we need to click on advance. But if that's the expected behavior then it's okay as it is.

**Comment by andyzito** [comment]
I can see both sides of this. I do feel like it's not a best practice to add a setting to the inline reply, when it seems to be designated as settings-less. That said, obviously users may be confused by the advanced button. Requesting weigh in from @mackensen @kwiliarty

**Comment by kwiliarty** [comment]
I suspect that few users will find their way into the advanced interface on their own, but like you @azito122 , I can see both sides. On balance I feel that it would probably be better to include an option in the inline interface, but I don't feel strongly.

**Comment by mackensen** [comment]
I think it would make sense to expose the setting for a forum where anonymity is optional. Users already see one checkbox for "Reply privately"; I could see adding "Reply anonymously." This would bring the behavior in line with the always anonymous forum, where you can use the inline reply and keep your anonymity since everything gets anonymized.

**Comment by kwiliarty** [comment]
The analogy with private replies is persuasive and inclines me more strongly toward including the anonymity option for inline replies.

**Comment by mackensen** [comment]
The fix will be incorporated into the next stable releases of the LAE, which trail core Moodle by a week. That's looking like mid-May right now. @rlorenzo, thanks again for the report.
